/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package catalogojuegos;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisg
 */
public class FrmJuegos extends javax.swing.JFrame {

    /**
     * Creates new form FrmJuegos
     */
    public FrmJuegos() {
        this.listaJuegos = new ArrayList<>();
        JuegoPC juego = new Adapter(new JuegoComputadora("Devil May Cry 5", PegiRatingEdad.P18, 50000000.00, 2048, 35840, 8192, 4, 3.40));
        JuegoPC juego2 = new Adapter(new JuegoComputadora("Star Wars Jedi: Fallen Order", PegiRatingEdad.P16, 50000000.00, 1024, 56320, 8192, 4, 3.40));
        JuegoPC juego3 = new Adapter(new JuegoComputadora("Doom Eternal", PegiRatingEdad.P18, 50000000.00, 2048, 35840, 8192, 4, 3.40));
        JuegoPC juego4 = new Adapter(new JuegoComputadora("Red Dead Redemption 2", PegiRatingEdad.P18, 50000000.00, 2048, 35840, 8192, 4, 3.40));
        JuegoPC juego5 = new Adapter(new JuegoComputadora("God of War", PegiRatingEdad.P18, 50000000.00, 2048, 35840, 8192, 4, 3.40));
        
        listaJuegos.add(juego);
        listaJuegos.add(juego2);
        listaJuegos.add(juego3);
        listaJuegos.add(juego4);
        listaJuegos.add(juego5);
        initComponents();
        
        this.cargarComboBox();
    }
    
    private void cargarComboBox(){
        for(int i = 0; i < listaJuegos.size(); i++){
            String titulo = listaJuegos.get(i).getTitulo();
            cajaCombinadaJuegos.addItem(titulo);
        }
    }
    
    private void mostrarJuego(){
        int indice = cajaCombinadaJuegos.getSelectedIndex();
        JuegoPC juego = listaJuegos.get(indice);
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaJuegos.getModel();
        modeloTabla.setRowCount(0);
        Object[] fila = new Object[8];
        fila[0] = juego.getTitulo();
        fila[1] = juego.getEdadPegi();
        fila[2] = juego.esJuegoTripleA();
        fila[3] = juego.getRequerimientos().getGpuGb();
        fila[4] = juego.getRequerimientos().getHDDGb();
        fila[5] = juego.getRequerimientos().getRAMGb();
        fila[6] = juego.getRequerimientos().getCoresNum();
        fila[7] = juego.getRequerimientos().getCpuGhz();
        modeloTabla.addRow(fila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaCombinadaJuegos = new javax.swing.JComboBox<>();
        panelTablaJuegos = new javax.swing.JScrollPane();
        tablaJuegos = new javax.swing.JTable();
        botonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista de Juegos");

        tablaJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Edad PEGI", "Es AAA", "GPU min (GB)", "Almacenamiento min (GB)", "RAM (GB)", "Num. Núcleos", "Velocidad (GHZ)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelTablaJuegos.setViewportView(tablaJuegos);

        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(cajaCombinadaJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(botonMostrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTablaJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCombinadaJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrar))
                .addGap(18, 18, 18)
                .addComponent(panelTablaJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        this.mostrarJuego();
    }//GEN-LAST:event_botonMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrar;
    private javax.swing.JComboBox<String> cajaCombinadaJuegos;
    private javax.swing.JScrollPane panelTablaJuegos;
    private javax.swing.JTable tablaJuegos;
    // End of variables declaration//GEN-END:variables
    List<JuegoPC> listaJuegos;
}
